#import "../style.typ": *

= Value interactions

Write $t arrow.r_v u$ for one value interaction. This relation contains the
local graph rewrites of the calculus; the next chapter specifies which local
redexes are demanded when computing WHNF. Every rule is closed under alpha
renaming, and names introduced by a rule are fresh.

== Application

#rulebox([APP–LAM], [
  A relevant lambda substitutes its argument without evaluating it:
  $ (lambda^1 x : A dot t) space u arrow.r_v t[x := u]. $
])

#rulebox([APP–ERASE], [
  An erased lambda discards its argument:
  $ (lambda^0 x : A dot t) space u arrow.r_v "erase"(u) ; t. $

  The semicolon denotes a pair of independent rewrites: the erased graph is
  reclaimed while evaluation continues with $t$.
])

#rulebox([APP–SUP], [
  Application distributes over a superposed function and duplicates the
  argument with the same label:
  $
    (&^ell {f, g}) space u
    arrow.r_v
    delta^ell u_0,u_1 := u space "in" space
      &^ell {f space u_0, g space u_1}.
  $
])

APP–LAM and APP–SUP are dual: one eliminates a lambda/application pair, while
the other propagates application through a superposition and creates a
duplication.

== Capability dispatch

Rigid values may provide properties and operators through their runtime type
descriptors. The notation $"descriptor"(v) => "Record"(L,P,O)$ is defined in
Chapter 7. Descriptor observation does not consume $v$.

#rulebox([PROPERTY], [
  If $P(p)=(S,m)$ and implementation $m$ is present, then
  $
    v dot p arrow.r_v m space v.
  $
  Stored fields use the accessor implementation generated by their product
  layout. A signature-only requirement has no implementation and cannot itself
  service run-time access.
])

#rulebox([OPERATOR], [
  If $O(o)=(S,m)$ and implementation $m$ is present, then
  $
    v space o space u arrow.r_v (m space v) space u.
  $
  The implementation is responsible for the receiver and right operand exactly
  once; its signature is checked independently by type evaluation.
])

#rulebox([APP–CALL], [
  If a demanded rigid function value is neither a lambda nor a superposition,
  application consults its distinguished `Call` operator. With implementation
  $m$,
  $
    v space u arrow.r_v (m space v) space u.
  $
  Absence of a closed `Call` entry or of its implementation produces `error`.
])

#rulebox([TYPE–COMPOSE], [
  When $A$ and $B$ regularize to type values and their consistent meet exists,
  $A+B$ reduces to that signature-only meet. A demonstrated conflict reduces to
  `error`; a stuck operand leaves composition stuck.
])

== Duplication

#rulebox([DUP–SUP, equal labels], [
  Equal labels annihilate:
  $
    delta^ell x_0,x_1 := &^ell {a,b} space "in" space t
    arrow.r_v t[x_0 := a, x_1 := b].
  $
])

#rulebox([DUP–SUP, distinct labels], [
  If $ell != k$, duplication commutes with superposition:
  $
  delta^ell x_0,x_1 := &^k {a,b} space "in" space t
  arrow.r_v
  delta^ell a_0,a_1 := a space "in" space
  delta^ell b_0,b_1 := b space "in" space
  t[
    x_0 := &^k {a_0,b_0},
    x_1 := &^k {a_1,b_1}
  ].
  $
])

#rulebox([DUP–LAM], [
  A duplicated lambda shares its body. With fresh $y_0,y_1,b_0,b_1$:
  $
  delta^ell f_0,f_1 := lambda^q x:A dot t space "in" space u
  arrow.r_v
  delta^ell b_0,b_1 :=
    t[x := &^ell {y_0,y_1}]
  space "in" space
    u[
      f_0 := lambda^q y_0:A dot b_0,
      f_1 := lambda^q y_1:A dot b_1
    ].
  $

  The body is not copied eagerly. Its single graph is placed behind a new
  duplication, and the two binders are represented by one superposition.
])

For a rigid $n$-ary constructor $K$ whose children are affine, duplication is
defined uniformly rather than by an eager copy:

#rulebox([DUP–RIGID], [
  Let $D_j(c) = delta^ell a_j,b_j := t_j space "in" space c$. Then
  $
    delta^ell x_0,x_1 := K(t_1, ..., t_n) space "in" space u
    arrow.r_v D_1(dots D_n(u') dots),
  $
  where
  $
    u' = u[x_0 := K(a_1,...,a_n),
             x_1 := K(b_1,...,b_n)].
  $

  A nullary rigid value duplicates immediately. Type records, sorts, dependent
  products, and atomic values are rigid for this rule. Implementations may use
  specialized rules that are observationally equivalent.
])

== Erasure and error

Erasure owns its operand and produces no value. It propagates structurally:

#rulebox([ERASE–RIGID], [
  $ "erase"(K(t_1,...,t_n)) arrow.r_v "erase"(t_1); ... ; "erase"(t_n). $

  Erasing a superposition erases both alternatives. Erasing one projection of
  an unresolved duplication transfers ownership to the surviving projection;
  erasing both projections erases the duplicand. These ownership effects do not
  change the read-back term produced by the abstract rules.
])

`error` is a first-class eraser. When it reaches an eliminator, it erases the
other owned operands and remains `error`; for example,
$"error" space u arrow.r_v "erase"(u); "error"$. This behavior propagates a
projection failure without inventing an error type.

== Interaction invariants

Each interaction preserves affinity: every owned child on the left has exactly
one owner or erasure action on the right. A rule may expose more syntax, but it
does not duplicate computation except through an explicit DUP. Labels are
semantic identities, not textual names; alpha-renaming a fresh label preserves
the term.

The kernel does not impose a global redex order. Independent interactions may
proceed concurrently. A reduction budget counts successful local interactions,
not traversal or failed attempts to expose a redex.
